"""Initial

Revision ID: 7325dc2c34ca
Revises: 
Create Date: 2022-06-01 01:16:56.008175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7325dc2c34ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
